# Tomcat Server

server:
  port: 8084
  
  
# Logger
logging.level:
  web: DEBUG
  '[com.ocean.accounting]': DEBUG

# Database Settings
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/accountingdb
    username: root
    password: Dubblin080@